# -*- coding: utf-8 -*-
"""Demo_Deployment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eUMGwGst3juE4unmx4yc-ER87T-w4MKo

# **Classroom Demo: Student Pass/Fail Predictor**

### ***Business Scenario***

A school teacher wants a simple application where they can enter a student's name and marks to quickly determine whether the student has passed or failed.

Instead of manually checking each student's marks, the teacher uses a simple web application built with Streamlit.

### ***Problem Statement***

Develop a simple Streamlit application that allows a teacher to:

1. Enter the student's name
2. Enter the student's marks
3. Click a button
4. Display whether the student has Passed or Failed

A student is considered:

1. Pass → Marks ≥ 35
2. Fail → Marks < 35

# **Step 1: Install Streamlit**
"""

#!pip install streamlit

"""# **Step 2 : Streamlit code for Implementation**"""

import streamlit as st

# Title
st.title("🎓 Student Result Predictor")

# User Inputs
name = st.text_input("Enter Student Name")

marks = st.number_input("Enter Marks", min_value=0, max_value=100)

# Button
if st.button("Check Result"):

    if marks >= 35:
        st.success(f"Congratulations {name}! You Passed.")
    else:
        st.error(f"Sorry {name}! You Failed.")

